name: Simple GitHub Actions workflow

on: [push]

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.6.0"
      - run: npm install
      - run: npm run build --if-present
      - run: |
          echo "build Completed successfully!"

      -name: Deploy to GH Pages
       uses: peaceiris/actions-gh-pages@v3
       with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public
